<?php

namespace FP\PerfSuite\Services\Cache\ObjectCacheManager;

/**
 * Genera il contenuto del drop-in per object cache
 * 
 * @package FP\PerfSuite\Services\Cache\ObjectCacheManager
 * @author Francesco Passeri
 */
class DropInGenerator
{
    /**
     * Genera il contenuto del drop-in
     */
    public function generate(string $backend): string
    {
        $template = <<<'PHP'
<?php
/**
 * Object Cache Drop-In
 * Generated by FP Performance Suite
 * 
 * Backend: %s
 * Date: %s
 * 
 * @package FP\PerfSuite
 */

// Don't load directly
if (!defined('ABSPATH')) {
    die('-1');
}

// Load the appropriate object cache implementation
%s
PHP;
        
        $implementation = $this->getBackendImplementation($backend);
        
        return sprintf(
            $template,
            strtoupper($backend),
            date('Y-m-d H:i:s'),
            $implementation
        );
    }

    /**
     * Ottiene l'implementazione per il backend specifico
     */
    private function getBackendImplementation(string $backend): string
    {
        $implementations = [
            'redis' => $this->getRedisImplementation(),
            'memcached' => $this->getMemcachedImplementation(),
            'apcu' => $this->getApcuImplementation(),
        ];
        
        return $implementations[$backend] ?? '';
    }

    /**
     * Implementazione Redis
     */
    private function getRedisImplementation(): string
    {
        // Usa il plugin Redis Object Cache se disponibile
        $redisPluginFile = WP_PLUGIN_DIR . '/redis-cache/includes/object-cache.php';
        
        if (file_exists($redisPluginFile)) {
            return "require_once '" . $redisPluginFile . "';";
        }
        
        // CRITICAL: Non possiamo implementare Redis qui perché questo file
        // viene caricato troppo presto nel ciclo di vita di WordPress.
        // Raccomandiamo l'installazione di un plugin dedicato.
        return <<<'PHP'
/**
 * ATTENZIONE: Per utilizzare Redis Object Cache è necessario installare
 * un plugin dedicato come "Redis Object Cache" di Till Krüss.
 * 
 * Non è possibile implementare Redis direttamente in questo drop-in
 * perché viene caricato troppo presto nel bootstrap di WordPress.
 * 
 * Per ora, WordPress utilizzerà la cache in memoria standard.
 */
return;
PHP;
    }

    /**
     * Implementazione Memcached
     */
    private function getMemcachedImplementation(): string
    {
        $memcachedPluginFile = WP_CONTENT_DIR . '/object-cache-memcached.php';
        
        if (file_exists($memcachedPluginFile)) {
            return "require_once '" . $memcachedPluginFile . "';";
        }
        
        return <<<'PHP'
/**
 * ATTENZIONE: Per utilizzare Memcached è necessario un drop-in specifico.
 * 
 * Non è possibile implementare Memcached direttamente in questo file
 * perché viene caricato troppo presto nel bootstrap di WordPress.
 * 
 * Per ora, WordPress utilizzerà la cache in memoria standard.
 */
return;
PHP;
    }

    /**
     * Implementazione APCu
     */
    private function getApcuImplementation(): string
    {
        return <<<'PHP'
/**
 * ATTENZIONE: L'implementazione APCu richiede un drop-in specifico.
 * 
 * Non è possibile implementare APCu direttamente in questo file
 * perché viene caricato troppo presto nel bootstrap di WordPress.
 * 
 * Per ora, WordPress utilizzerà la cache in memoria standard.
 */
return;
PHP;
    }
}















