<?php

namespace FP\PerfSuite\Services\Intelligence\CDNExclusionSync;

use function json_encode;
use function preg_quote;
use const JSON_PRETTY_PRINT;
use const JSON_UNESCAPED_UNICODE;

/**
 * Genera ed esporta regole CDN
 * 
 * @package FP\PerfSuite\Services\Intelligence\CDNExclusionSync
 * @author Francesco Passeri
 */
class CDNRulesGenerator
{
    /**
     * Genera regole CDN in formato standard
     */
    public function generate(array $exclusions): array
    {
        $rules = [
            'version' => '1.0',
            'generated_at' => time(),
            'rules' => [],
        ];

        foreach ($exclusions as $exclusion) {
            $rules['rules'][] = [
                'pattern' => $exclusion['url'],
                'action' => 'no_cache',
                'reason' => $exclusion['reason'],
                'priority' => $exclusion['priority'],
                'type' => $exclusion['type'],
            ];
        }

        return $rules;
    }

    /**
     * Esporta regole CDN in formato JSON
     */
    public function export(array $rules, string $format = 'json'): string
    {
        switch ($format) {
            case 'json':
                return json_encode($rules, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE);
            
            case 'nginx':
                return $this->exportToNginx($rules);
            
            case 'apache':
                return $this->exportToApache($rules);
            
            default:
                throw new \InvalidArgumentException('Formato non supportato: ' . $format);
        }
    }

    /**
     * Esporta regole in formato Nginx
     */
    private function exportToNginx(array $rules): string
    {
        $nginx = "# CDN Exclusion Rules for Nginx\n";
        $nginx .= "# Generated by FP Performance Suite\n\n";
        
        foreach ($rules['rules'] as $rule) {
            $nginx .= "location ~* " . preg_quote($rule['pattern'], '/') . " {\n";
            $nginx .= "    add_header Cache-Control \"no-cache, no-store, must-revalidate\";\n";
            $nginx .= "    add_header Pragma \"no-cache\";\n";
            $nginx .= "    add_header Expires \"0\";\n";
            $nginx .= "}\n\n";
        }
        
        return $nginx;
    }

    /**
     * Esporta regole in formato Apache
     */
    private function exportToApache(array $rules): string
    {
        $apache = "# CDN Exclusion Rules for Apache\n";
        $apache .= "# Generated by FP Performance Suite\n\n";
        
        foreach ($rules['rules'] as $rule) {
            $apache .= "<LocationMatch \"" . preg_quote($rule['pattern'], '/') . "\">\n";
            $apache .= "    Header set Cache-Control \"no-cache, no-store, must-revalidate\"\n";
            $apache .= "    Header set Pragma \"no-cache\"\n";
            $apache .= "    Header set Expires \"0\"\n";
            $apache .= "</LocationMatch>\n\n";
        }
        
        return $apache;
    }
}















