name: Build plugin zip

on:
  push:
    tags:
      - 'v*'

env:
  PLUGIN_SLUG: fp-performance-suite

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none

      - name: Install dependencies
        run: composer install --no-dev --prefer-dist --no-interaction --optimize-autoloader

      - name: Optimize autoload
        run: composer dump-autoload -o --classmap-authoritative

      - name: Prepare build directory
        run: |
          rm -rf "build/${PLUGIN_SLUG}"
          mkdir -p "build/${PLUGIN_SLUG}"
          rsync -a --delete \
            --exclude=.git \
            --exclude=.github \
            --exclude=tests \
            --exclude=docs \
            --exclude=node_modules \
            --exclude=*.md \
            --exclude=.idea \
            --exclude=.vscode \
            --exclude=build \
            --exclude=.gitattributes \
            --exclude=.gitignore \
            ./ "build/${PLUGIN_SLUG}/"

      - name: Create zip archive
        env:
          ZIP_NAME: ${{ env.PLUGIN_SLUG }}-${{ github.ref_name }}
        run: |
          cd build
          zip -r "${ZIP_NAME}.zip" "${PLUGIN_SLUG}"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: plugin-zip
          path: build/${{ env.PLUGIN_SLUG }}-${{ github.ref_name }}.zip
          if-no-files-found: error
