name: Update Plugin ZIP

on:
  push:
    branches: [ main ]
    paths:
      - 'fp-performance-suite/src/**'
      - 'fp-performance-suite/assets/**'
      - 'fp-performance-suite/views/**'
      - 'fp-performance-suite/*.php'
      - 'fp-performance-suite/readme.txt'

env:
  PLUGIN_SLUG: fp-performance-suite

jobs:
  update-zip:
    runs-on: ubuntu-latest
    # Evita loop infiniti ignorando commit del bot
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none
      
      - name: Prepare build directory
        run: |
          mkdir -p "build/${PLUGIN_SLUG}"
          cd "${PLUGIN_SLUG}"
          find . -type f \( -name "*.php" -o -name "*.css" -o -name "*.js" -o -name "*.pot" -o -name "*.txt" \) \
            ! -path "*/tests/*" \
            ! -path "*/docs/*" \
            ! -path "*/examples/*" \
            ! -path "*/tools/*" \
            ! -path "*/bin/*" \
            ! -path "*/.git/*" \
            ! -path "*/node_modules/*" \
            ! -path "*/build/*" \
            ! -path "*/vendor/*" \
            ! -name "*composer*" \
            ! -name "*.md" \
            ! -name "*.xml.dist" \
            ! -name "*.neon.dist" \
            ! -name "*.sh" \
            -exec bash -c 'mkdir -p "../build/${PLUGIN_SLUG}/$(dirname "{}")" && cp "{}" "../build/${PLUGIN_SLUG}/{}"' \;
          
          # Copia file essenziali
          cp LICENSE readme.txt uninstall.php "../build/${PLUGIN_SLUG}/" 2>/dev/null || true
      
      - name: Create ZIP
        run: |
          cd build
          zip -r "${PLUGIN_SLUG}.zip" "${PLUGIN_SLUG}" -q
          mv "${PLUGIN_SLUG}.zip" "../${PLUGIN_SLUG}.zip"
      
      - name: Verify ZIP content
        run: |
          echo "📊 Verifica contenuto ZIP..."
          PAGESPEED_COUNT=$(unzip -p "${PLUGIN_SLUG}.zip" "${PLUGIN_SLUG}/src/Admin/Pages/Assets.php" 2>/dev/null | grep -c "PageSpeed" || echo "0")
          FILE_COUNT=$(unzip -l "${PLUGIN_SLUG}.zip" | tail -1 | awk '{print $2}')
          echo "✅ File inclusi: ${FILE_COUNT}"
          echo "✅ PageSpeed features: ${PAGESPEED_COUNT}"
      
      - name: Commit updated ZIP
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Aggiungi sempre il ZIP, git rileverà se è cambiato
          git add "${PLUGIN_SLUG}.zip"
          
          # Verifica se ci sono modifiche da committare
          if git diff --staged --quiet; then
            echo "✅ ZIP già aggiornato, nessun commit necessario"
          else
            VERSION=$(grep "Version:" "${PLUGIN_SLUG}/${PLUGIN_SLUG}.php" | head -1 | sed 's/.*Version: //' | tr -d ' ')
            git commit -m "chore: Update plugin ZIP to v${VERSION} [skip ci]"
            git push
            echo "✅ ZIP aggiornato e committato (v${VERSION})"
          fi
      
      - uses: actions/upload-artifact@v4
        with:
          name: fp-performance-suite-latest
          path: fp-performance-suite.zip
